---
strategy: polling
no_screen_padding: 
dark_mode: 
static_data: 
polling_verb: GET
framework_version: 3.1.1
serverless_language: node
polling_url: https://trmnl.diane-feedback-relay.workers.dev/sydsvenskan.json?source=frontpage-v1&reader={{ reader }}
polling_headers: 
polling_body: 
id: 176724
custom_fields:
- keyname: reader
  name: Reader tag
  field_type: string
  optional: true
  help_text: Leave empty.
- keyname: style
  name: Utseende
  field_type: select
  options:
  - Med bild: image
  - Bara lista: list
  default: image
- keyname: author_bio
  name: About This Plugin
  field_type: author_bio
  description: Sydsvenskan Latest News was created by Tim.
  github_url: https://github.com/tkilaker/trmnl-recipes
  email_address: tkilaker@icloud.com
name: Sydsvenskan Latest News
refresh_interval: 15
