watch:
  - src/**/*.liquid
  - src/settings.yml

custom_fields:
  page_number: 200
  show_subpages: false

time_zone: Europe/Stockholm

variables:
  data:
    - num: "101"
      title: "SVT Text"
      content: "<div>SVT Text-TV page content here</div>"
      content_plain: |
        101 SVT Text torsdag 06 nov 2025


                                     SVT Text

           * = efter kl 12

          Man skjuten till döds i Bromma.... 106

          Oväntat hög inflation i oktober... 107

        * Hälften av Stegra-kapitalet säkrat 108

          Regeringen: Anmäl kontantutförsel. 109

          Brå: Var fjärde politiker hotas... 110

          Misstänks ha förberett terrordåd.. 111

          Man döms för mord på flickvän..... 112

        * Misstänkt fusk med p-vakter....... 113

           Utrikes 104  Sport 300  Innehåll 700
