---
strategy: polling
no_screen_padding: 
dark_mode: 
static_data: 
polling_verb: GET
framework_version: 3.1.1
serverless_language: node
polling_url: https://api.open-meteo.com/v1/forecast?latitude={{ latitude }}&longitude={{ longitude }}&current=temperature_2m,apparent_temperature,precipitation,weather_code,wind_speed_10m,wind_gusts_10m,wind_direction_10m&hourly=temperature_2m,precipitation_probability,precipitation,weather_code&daily=temperature_2m_max,temperature_2m_min,precipitation_sum,precipitation_probability_max,weather_code&timezone=Europe%2FStockholm&forecast_days=3&wind_speed_unit=ms
polling_headers: 
polling_body: 
custom_fields:
- keyname: place
  name: Plats
  field_type: string
  default: Malmö
- keyname: latitude
  name: Latitud
  field_type: string
  default: '55.605'
- keyname: longitude
  name: Longitud
  field_type: string
  default: '13.000'
name: Väder nu
refresh_interval: 30
